### ISSUE TITLE
Error using Orca 5.0.1

### ISSUE THREAD

**Issue by attiliocn** [grimme-lab/CENSO#21]
Hello! 

I am getting the following error when trying to use CENSO for a conformer ensemble. Although the ORCA Version is set to 5.0.1 in my .censorc config file, it appears on the output as 5.01. I briefly looked into the source code and it appears to have a version check for ORCA, where a function split the version number at the dots. Could the problem be related to this version check? Also, other electronic methods such as r2scan-3c doesn't work on my CENSO setup, even though they are available on the ORCA currently installed in my computer. 

Thanks in advance for your support!

**Additional Info**

CENSO Version: 1.1.2
.censorc Version:  1.1.2
ORCA Version: 5.0.1
output excerpt:

```
------------------------------------------------------------
               PATHS of external QM programs                
------------------------------------------------------------

The following program paths are used:
    ORCA:         /home/attilio/opt/oorca/
    ORCA Version: 5.01
    xTB:          /home/attilio/opt/xtb-6.4.1/bin/xtb


****************************************************************************************************
ERROR:       The functional (func0) b97-d3(0) is not implemented with the orca program package.

****************************************************************************************************

ERROR:       CENSO can not continue due to input errors!

Going to exit!

```

**Comment by fabothch** [comment]
Hi,

For func0 (the functional chosen for part0) you can chose from:

    Functionals that can be employed by ORCA for func0:

    b97-3c, pbe-novdw, tpss-d3, b3lyp, pbe0-d4, b3lyp-d3, b3lyp-d4, pbe-d3(0), pw6b95,
    pw6b95-d3, pbe0-d3, pbe-d3, wb97x-d3bj, pw6b95-novdw, b3lyp-3c, b3lyp-d3(0), pw6b95-d4, b3-lyp,
    r2scan-3c, tpss-d3(0), b97-d3, tpss-novdw, pbe-d4, pbeh-3c, b3lyp-novdw, wb97x-d4, wb97x-v,
    tpss-d4, pbe0-novdw, pbe0-d3(0), wb97x-d3, pw6b95-d3(0), pbe0, pbe, tpss, 
  
CENSO has no information on how to setup a b97-d3(0) calculation using ORCA and therefore informs the user that this choice of func0 with ORCA can not be used. So you can choose another functional.

Concerning your report that r2scan-3c does not work: what does this mean? Do you get an error, don't calculations start or do they crash? I just checked it on two machines and do not see any problem.

Maybe you can try using the latest release which was just updated recently: [censo v.1.1.2](https://github.com/grimme-lab/CENSO/releases/tag/v.1.1.2)

All the best,

Fabian

**Comment by attiliocn** [comment]
Hi Fabian,

> CENSO has no information on how to setup a b97-d3(0) calculation using ORCA and therefore informs the user that this choice of func0 with ORCA can not be used. So you can choose another functional.
Oh, that was my fault indeed. I tried to run a calculation in ORCA using b97-d and it worked, so I assumed there was a problem with CENSO. The problem is that b97-d is not b97-d3, of course...  

> Concerning your report that r2scan-3c does not work: what does this mean? Do you get an error, don't calculations start or do they crash? I just checked it on two machines and do not see any problem.
This is a problem I had when using previous versions of ORCA because this method was not implemented yet. So when I updated to ORCA 5.0.1 and CENSO current version (1.1.2) and still got the error I thought that maybe the version of ORCA was not being recognized by CENSO. However, the real problem is a typo, as the input recognize r2scan-3c but not r2scan3c as I was trying to use. 

```
****************************************************************************************************
ERROR:       The functional (func0) r2scan3c is not implemented with the orca program package.

ERROR:       The functional r2scan3c is not available for part0.

****************************************************************************************************

ERROR:       CENSO can not continue due to input errors!

Going to exit!
```

All in all, both problems are on me! Sorry for that

**Comment by fabothch** [comment]
No problem at all!
Best,
Fabian
