### ISSUE TITLE
Freeze coordinates

### ISSUE THREAD

**Issue by andre-cloud** [grimme-lab/CENSO#26]
I've generated an xyz file with CREST using constraints on two bonds and an angle. Is there a method to refine the conformers? 

This is the constraints file used for crest calculation
```
$constrain
atoms: 63, 126, 129
force constant=0.5
reference=TS.xyz
$metadyn
atoms:1-62, 64-125, 127-128, 130
$end
```

**Comment by fabothch** [comment]
Hi,

currently, this is not implemented but has now been requested several times. I'll look into it, but it might take me some time to test it thoroughly.

Best,

Fabian

**Comment by andre-cloud** [comment]
Thanks so much for your work
