### ISSUE TITLE
Wrong charge and spin for ancopt in part 2

### ISSUE THREAD

**Issue by froze-jameel** [grimme-lab/CENSO#29]
Hello,
In my calculations i am using a charged molecules and write charge in censorc file as 1 and spin 0. However, in part 2 ancopt output the charge and spin of molecules are wrong (See below).
Could you help me resolving this issue.

Censorc

$CRE SORTING SETTINGS:
$GENERAL SETTINGS:
nconf: all                       # ['all', 'number e.g. 10 up to all conformers'] 
charge: +1                        # ['number e.g. 0'] 
unpaired: 0                      # ['number e.g. 0'] 
solvent: h2o                     # ['gas', 'acetone', 'acetonitrile', 'aniline', 'benzaldehyde', 'benzene', 'ccl4', '...'] 
prog_rrho: xtb                   # ['xtb'] 
temperature: 298.15              # ['temperature in K e.g. 298.15'] 
trange: [273.15, 378.15, 5]      # ['temperature range [start, end, step]'] 
multitemp: on                    # ['on', 'off'] 
evaluate_rrho: on                # ['on', 'off'] 

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ancopt part
           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : /mechthild/software/apps/xtb-6.4.0/bin/xtb coord --opt normal --tm -I opt.inp
          hostname                   : node026
          coordinate file            : coord
          number of atoms            :                    24
          number of electrons        :                    49
          charge                     :                     0
          spin                       :                   0.5
          first test random number   :      0.66531624437863

**Comment by fabothch** [comment]
Hi, 
xtb is only used as a driver for ANCopt and the external call to either TM or ORCA has the correct charge and spin information. In the case of TM this is considered during the creation of the _control_ file and for ORCA this is written into the file _inp_ . 
You can have a look at your orca input file or control file and the correct charge information should be present there. However, I can see that this seemingly wrong charge info in xtb is confusing and I will remedy this in the next update.

Best,

Fabian

**Comment by fabothch** [comment]
Addressed in #30
