### ISSUE TITLE
calling some functions add automatically d4

### ISSUE THREAD

**Issue by jouteurestaque** [grimme-lab/CENSO#33]
hi
I am still using this version for a bit so did not try the new one.
But I noticed whatever I tried to call like b3lyp or pbe0, it adds the d4 automatically at the start of the censo program.

Thanks for this great program

**Comment by fabothch** [comment]
Hi,
this is intended behavior to be in line with older versions where pbe0 or b3lyp would map to pbe0-d3 or b3lyp-d3.
If you want to use a density functional without any dispersion correction you have to call them like: b3lyp-novdw or pbe0-novdw. The available functionals without  dispersion correction should be listed when calling `censo -tutorial`

**Comment by jouteurestaque** [comment]
indeed thanks now I see them. did not no what they were indeed.
thank you
I have a couple I will post
