### ISSUE TITLE
ERROR with the SHARK of orca when calling large basis

### ISSUE THREAD

**Issue by jouteurestaque** [grimme-lab/CENSO#34]
Hi
I am using the old 1.1.2 version so maybe the last 1.2.0 version was made for this problem.
calling B3LYP and cc-pVDZ for TTMS on the NMR module mode made it crash for matrice problem
the solution provided but the ORCA forum was to remove shark
> %shark PartialGCFlag 0 end

I am guessing we can use the new editable  censo_ORCA_editable.dat I could implement this line? 
THANKS

**Comment by jouteurestaque** [comment]
related to that new editable dat, I guess It should resolve problem calling too much memory for NMR
it failed if I keep the %MaxCore 8000

**Comment by lmseidler** [comment]
This can now be done using the new template file system.
