### ISSUE TITLE
Calculating 13C and 1H spectra without 13C-1H coupling

### ISSUE THREAD

**Issue by andysardjan** [grimme-lab/CENSO#36]
Hey all,
Very impressed with CENSO! One thing however, I would like to calculate 1H spectra and (uncoupled) 13C spectra seperately. Now I have my C13-coupled 1H spectra (which is quite exotic!). In orca I would just do this by excluding carbon from the coupling calculation. What is your recommendation? Is there a setting for ANMR to exclude the carbon couplings? Or should I dig around my .json files to set the coupling to 0?

**Comment by fabothch** [comment]
Hi,

> Now I have my C13-coupled 1H spectra (which is quite exotic!)

I agree having **all** carbon nuclei and **all** hydrogen nuclei as nmr active elements in a molecule is kind of strange.
You can have a look at the [documentation](https://xtb-docs.readthedocs.io/en/latest/CENSO_docs/censo_nmr.html).
There you can see that you can switch nmr active elements on and off for ANMR.
This is done in the .anmrrc file.
Perform one ANMR calculation only for the 1H spectrum:
```
1  31.786    0.0    1
6  189.674   0.0   0
9  182.57    0.0    0
15 291.9     0.0    0
```
and once only the 13C spectrum:
```
1  31.786    0.0    0
6  189.674   0.0   1
9  182.57    0.0    0
15 291.9     0.0    0
```
So you have to run ANMR twice on the data produced by your CENSO calculation and get then two spectra.

Best,

Fabian

**Comment by andysardjan** [comment]
Ah thanks a lot! this works!
