### ISSUE TITLE
in between optimization cycle

### ISSUE THREAD

**Issue by jouteurestaque** [grimme-lab/CENSO#38]
Hi, I have the newest version 1.2 but it does not start at the last optimization cycle like that version is supposed to do.

Is it properly working??

*******************************CYCLE 1********************************

Starting 73 optimizations.
Running optimization in CONF1/r2scan-3c

a restart from a run which is at  cycle 2 already

***************************CYCLE 2********************************

Starting 73 optimizations.
Running optimization in CONF1/r2scan-3c

cheers

**Comment by fabothch** [comment]
Hi,
I do not fully understand your point.  What exactly is not recognized upon a restart? 
Do you mean the restart should start with cycle2 ??
If so, then this is intended behavior. Upon a restart, you could increase the number of considered conformers and for those, it would be the first iteration.

**Comment by jouteurestaque** [comment]
sorry for the confusion the first one starting at cycle 1 was the restart, the second was the one I was restarting.
But now that it is finished I can see that that Cycle 1 restart I think it is doing like before it redo the first cycle then because it has the ensojson previous file (and all the stuff imported)  at the end of the cycle 1 it has already converged some conformers that only be converged at cycle 2.
like the previous version I recall
[first.txt](https://github.com/grimme-lab/CENSO/files/9713071/first.txt)



[restart.txt](https://github.com/grimme-lab/CENSO/files/9713070/restart.txt)
