### ISSUE TITLE
<< Requiered package to calculate NMR >>

### ISSUE THREAD

**Issue by icamps** [grimme-lab/CENSO#39]
Hello,

I would like to start using CENSO to calculate the NMR spectra for some molecules.

I have to confess that I am a little confused about with software will I need. 

From the documentation, I understand that I will need:

- CREST (available from prof. Grimme Lab., free of charge)
- CENSO (available from prof. Grimme Lab., free of charge)
- ANMR (available from prof. Grimme Lab., free of charge)
- TURBOMOLE (commercial software that can be replaced with ORCA, free of charge)
- CEFINE (available from prof. Grimme Lab., free of charge, as an independent program but also include withing CENSO)
- COSMOTHERM (commercial software, didn't fine a replacement)

Is this right?

How to replace the COSMOTHERM software?

Thanks in advance.

**Comment by fabothch** [comment]
Hi,

yes you are correct several programs are needed for the calculation of NMR spectra with CENSO.
You will need:
* xTB (from the grimmelab) used with CREST for the creation of conformer ensembles and in CENSO for the computation of the thermostatistical contribution to free energy.
* CREST for the creation of conformer /rotamer ensembles (CRE).
* CENSO for the refinement of the CRE at DFT level and subsequent NMR property calculations. These refinement and property calculations can be performed by either TURBOMOLE or ORCA code.
* Cefine is only necessary for setting up TURBOMOLE calculations.(if required/wanted)
* Cosmotherm is used for the computation of the solvation free energy Gsolv and comes from cosmologic. The free alternative would be to use SMD from ORCA (inside CENSO there is an option for SMD or SMD_gsolv).
* ANMR for averaging the nmr properties and solving the spin hamiltonian: https://github.com/grimme-lab/enso/releases/tag/v.2.0.2 is provided in the latest release of the enso.

**Comment by icamps** [comment]
Thank you very much for the clarifications @fabothch
