### ISSUE TITLE
Abs. Entropy Calculation

### ISSUE THREAD

**Issue by amrhamedp** [grimme-lab/CENSO#40]
Hello,
Regarding the instructions provided here https://github.com/grimme-lab/mol-entropy : 
-Can you please provide an example input for the frequency calculation that you used for turbomole to obtain vibspectrum ?
-I would also appreciate if you provide an example for censo input to optimize the structure using DFT.

**Comment by fabothch** [comment]
Please contact the author of https://github.com/grimme-lab/mol-entropy for these details!
