### ISSUE TITLE
GNF2 for censo

### ISSUE THREAD

**Issue by jouteurestaque** [grimme-lab/CENSO#45]
HI.
I know this is an odd request, but would it be possible to add the gnf1 and 2 for censo.
I have trouble with the deprotonated crest for some tricky cmpounds, and the only possibility I found was using ORCA to do those deprotonate_0.xyz
would be quite handy if I could simulate a deprotonate with censo..on part 2

Thank you guys

**Comment by fabothch** [comment]
CENSO is used for refining geometries and (free) energies at a level higher than the semi empirical GFNn-xTB level. Therefore reoptimizing geometries with GFNn-xTB in Part2 is not our focus and/or necessary.
