### ISSUE TITLE
how to not use XTB optimizer

### ISSUE THREAD

**Issue by jouteurestaque** [grimme-lab/CENSO#46]
Hi
I would like to use the orca optimization for CeNSo noticing some big dfifference in anionic species.
But using the ANCOPT off, return in 
ERROR:       optimization in CONF1/r2scan-3c    not converged..

cannot find a explaination somewhere

Thank for your help

**Comment by fabothch** [comment]
The answer is quiet simple: within CENSO you can only use the ANCopt optimizer!
