### ISSUE TITLE
Part2 - optimization / optimization not converged / optimization crashed

### ISSUE THREAD

**Issue by C-unelma** [grimme-lab/CENSO#50]
Hello,

I may have found a problem I couldn't resolve yet with the part2 - optimization of CENSO. Each time, the optimization for each conformer crashed whereas .censorc may has been properly configured.

Going into details, when reading the "opt-part2.out" file, a "SIGSEGV: segmentation fault - invalid memory reference" is always returned.

I found that there is a problem with the "program call" at the beginning of the "Calculation Setup" using the coord file :

`/path-to-xtb/bin/xtb coord --opt lax --orca -I opt.inp`

When executing in a "CONF" folder this command-line, the same error is returned. Whereas, using,

`/path-to-xtb/bin/xtb coord --opt lax --prog orca -I opt.inp`

The calculation just runs fine with a normal termination of xtb.

I don't know yet if I may have made a mistake somewhere or if the problem comes from a small omission in the XTB code.

Here the command I used to execute CENSO : 

`censo --input crest_conformers.xyz -solvent chcl3 -cactive off > censo.out`

Here the specification of my system : 
- Ubuntu 22.04.2 LTS 64 bits
- Intel(R) Core i9-9880H CPU @ 2.30 GHz x 16
- 32.0 Gio (RAM)

XTB version : 6.6.0
CREST version : 2.12
CENSO version : 1.2.0
ANMR version : 3.5.1

ORCA version : 5.0.4

Environment variables : 
ulimit -s unlimited

My .censorc file, one of the input file of a conformer "opt.inp" and its output file "opt-part2.out" are given with the input file for ORCA "inp". The censo.out file is also joined in this issue.

[censorc.txt](https://github.com/grimme-lab/CENSO/files/11925670/censorc.txt)

[opt_inp.txt](https://github.com/grimme-lab/CENSO/files/11925672/opt_inp.txt)

[opt-part2_out.txt](https://github.com/grimme-lab/CENSO/files/11925675/opt-part2_out.txt)

[inp.txt](https://github.com/grimme-lab/CENSO/files/11925677/inp.txt)

[censo_out.txt](https://github.com/grimme-lab/CENSO/files/11925678/censo_out.txt)

**Comment by MtoLStoN** [comment]
Thank you for taking your time reporting this issue.
There is a known bug in xTB 6.6.0 with external Orca calculations (we should really release a bugfix release soon). You can either try an older xTB Version or use our [bleed](https://github.com/grimme-lab/xtb/releases/tag/bleed) build.
