### ISSUE TITLE
NMR chemical shift caluclations fail with ORCA and default settings

### ISSUE THREAD

**Issue by PeteGierth** [grimme-lab/CENSO#52]
In CENSO 1.2.0, default settings in the config file have:

**func: r2scan-3c** 
(for geom opt)
**funcS: pbe0**  
(for shielding calculations)
**basisS: def2-TZVP** 

Calling crenso with e.g.

**crenso -l1 -nmr chcl3 -T 8 > output.crenso**

the calculation completes including shielding but the output indicates:

**Writing .anmrrc!
ERROR:       The reference absolute shielding constant for element h could not be found!
             You have to edit the file .anmrrc by hand!
INFORMATION: The KeyError is: 'r2scan-3c'
ERROR:       The reference absolute shielding constant for element c could not be found!
             You have to edit the file .anmrrc by hand!
INFORMATION: The KeyError is: 'r2scan-3c'**

and the reference shielding is set to zero.

Inspection of censo_nmr_ref.json shows that indeed there are no ORCA values calculated with r2scan-3c for geometry optimisation for this combination of functional and basis set for the shielding calculation listed, only turbomole.

One can work around this easily either by using a different routine for the optimisation which has appropriate shieldings in the json file (b97-3c, pbeh-3c , or tpss ) or by adding the shielding constants for TMS calculated with r2scan-3c/pbe0/def2-TZVP to the json file.  
Manually geometry optimising TMS using r2scan-3c and calculating the shieldings at pbe0/def2-TZVP in ORCA, I get ~189.03 and 31.59 ppm for carbon and proton in chcl3

**Comment by lmseidler** [comment]
In the newest version the .anmrrc file is not generated automatically anymore, the reference shielding constants have to be added manually.
