### ISSUE TITLE
Can't install CENSO 2.0

### ISSUE THREAD

**Issue by FrancescoTalotta** [grimme-lab/CENSO#55]
Hello,

I was trying the new CENSO 2.0 but I can't install it properly. I exported the $PATH and $PYTHONPATH, but I get this output when I try to run `censo`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/francesco/CENSO/src/censo/__init__.py", line 1, in <module>
    from .configuration import configure
  File "/home/francesco/CENSO/src/censo/configuration.py", line 6, in <module>
    from .params import CENSORCNAME, ASSETS_PATH, USER_ASSETS_PATH
  File "/home/francesco/CENSO/src/censo/params.py", line 9, in <module>
    from .__version__ import __version__
ModuleNotFoundError: No module named 'censo.__version__'
```
Do you know how to solve this? 

Thank you

**Comment by johnwkeller54** [comment]
I am having the same problem. How was this solved?
John Keller

**Comment by FrancescoTalotta** [comment]
Hello, for me exporting `PYTHONPATH` and `PATH` did not work. I had to use `pip install .` to let it work.

**Comment by johnwkeller54** [comment]
When I do "pip install ." I get the following error message:
ERROR: Package 'censo' requires a different Python: 3.9.18 not in '>=3.10'
I have python3, python3.11 and python3.12 installed (including  -devel ) This is a Rocky Linux 9.2 system with kernel 5.14.

**Comment by FrancescoTalotta** [comment]
Hello, try to check if the `pip` you're using corresponds to the python version you want to use.

**Comment by johnwkeller54** [comment]
OK, I installed python3.12 pip and installed CENSO. However, I am getting an error message - I will open another issue.
For the record, here is what I have done:
OS: Rocky Linux 8.10  (user sally)
$ dnf install python3.12 python3.12-pip
$ git clone https://github.com/grimme-lab/CENSO.git
$ cd /home/sally/CENSO
$ python3.12 -m pip install .
    (Successfully installed censo-2.0.2.dev4+g06f5d36)
$ python3.12 -m --new-config
$ cd ~
$ cp censo2rc_NEW censo2rc

**Comment by lmseidler** [comment]
FYI: the __version__.py is created automatically by setuptools on building the package using pip. I haven't found a good solution to handle this if you choose to use CENSO without installing it with pip, the solution by @BeWater23 is the way you have to go in that case. However, in the long term we want CENSO to be accessible on PyPI. Therefore installing and using it with pip is supposed to become the conventional way of using CENSO.
