### ISSUE TITLE
"unrecognized argument" error

### ISSUE THREAD

**Issue by johnwkeller54** [grimme-lab/CENSO#56]
I am getting a "censo: error: unrecognized arguments: ./crest_conformers.xyz" when I run censo per the following:

$ cd <folder with crest_conformers.xyz>
$ python3.12 -m censo -inp ./crest_conformers.xyz

**Comment by FrancescoTalotta** [comment]
Hello I have got the same error. I believe there are some problems with the `cml_parser.py`. To let it work I commented out some lines in `cml_parser.py`: 
```
    #if not check_soft_requirements(args):
    #    raise argparse.ArgumentError(
    #        # None, "One of the soft requirements ('-inp', '-chrg', '-u') not met."
    #        None,
    #        "You must provide an input file via '-i'.")
```

**Comment by johnwkeller54** [comment]
Hi,
I did that and still gives same error.

**Comment by FrancescoTalotta** [comment]
Did you recompile the code with `pip install .` ?

**Comment by johnwkeller54** [comment]
Yes:
-----------------
$ python3.12 -m pip install .
...
Successfully built censo
Installing collected packages: censo
  Attempting uninstall: censo
    Found existing installation: censo 2.0.2.dev4+g06f5d36
    Uninstalling censo-2.0.2.dev4+g06f5d36:
      Successfully uninstalled censo-2.0.2.dev4+g06f5d36
Successfully installed censo-2.0.2.dev4+g06f5d36.d20241002
--------------------------
lines 529-533 of cml_parser.py:

    #if not check_soft_requirements(args):
    #    raise argparse.ArgumentError(
    #        # None, "One of the soft requirements ('-inp', '-chrg', '-u') not met."
    #        None,
    #        "You must provide an input file via '-inp'.")
-------------------------
JK

**Comment by johnwkeller54** [comment]
Repeated install, edit cml_parser.py, re-compile with python3.11.  Same result.

**Comment by FrancescoTalotta** [comment]
Hello, that's how I perform a calculation with the new version: 

`censo -i $geom -c 2 -s acetonitrile -O 4 --maxcores 16 > $CurrDir/censo.out`

I use the `-i` option for the geometry

**Comment by adamhorvath99** [comment]
I have the same issue

**Comment by johnwkeller54** [comment]
Dear Developers:
If censo is broken, please fix it or tell us how to modify it.
If censo is not broken, please provide more detailed directions for running a basic censo calculation.

If I run "python3.12 -m censo -h"
I get help messages which include "-i, --help INP Relative path to ensemble.."

If I use "python3.12 -m censo -i crest_conformers.xyz > censo.out"
I get the error message "You must provide an input file via '-inp'."

If I use "python3.12 -m censo -inp crest_conformers.xyz > censo.out"
I get the error message "...censo: error: unrecognized arguments: crest_conformers.xyz"

Why is censo not accepting my input??

John

**Comment by drmewes** [comment]
Not the developer, but I had a brief glance at the code for argparse() in cml_parser.py.

What I can see there is that input is accepted as "-i" and "--input", but not as "-inp", so yes, the help is faulty (I guess this is a conflict resulting from the 1.2 -> 2.0 rewrite). Here is the function:

`groups[0].add_argument(
        "-i",
        "--input",
        dest="inp",
        type=str,
        help="Relative path to ensemble file, e.g. crest_conformers.xyz ",
    )`
    
And the error is thrown in:

`if not check_soft_requirements(args):
        raise argparse.ArgumentError(
            # None, "One of the soft requirements ('-inp', '-chrg', '-u') not met."
            None,
            "You must provide an input file via '-inp'.")`
    
You can try "--input", but I fear sth else is wrong, maybe having to do with the way how you call it...
Have you tried -input "crest_conformers.xyz"?

I am sure the developers will soon take a look and fix the issue.
Cheers,
Jan

**Comment by lmseidler** [comment]
Hi everyone and sorry for the late answer. The please check out the newest commit in the main branch. 
For the new version, it is required to give and input file via `-i` or `--inp` and the maximum number of cores CENSO is allowed to work with via `--maxcores`. The last version unfortunately included a fairly confusing error message. Hope this resolves the issue.

Leopold

**Comment by johnwkeller54** [comment]
OK! that works now! The 10-6-2024 version was installed. The command to for a basic job was
python3.12 - m censo --input "crest_conformers.xyz" --maxcores 4 > censo.out
Thank you Leopold, Jan, Adam, and Francesco
