### ISSUE TITLE
Censo 1.2 Constraint

### ISSUE THREAD

**Issue by adamhorvath99** [grimme-lab/CENSO#58]
Hello,

I want to apple geometrical constraint to censo 1.2 calcs. How is it possible?

**Comment by lmseidler** [comment]
Hi,

the previous versions of CENSO (1.2 is an old version) do no support geometric constraints. For this you would need to use the new 2.0 version. On how to apply the constraints refer to the documentation on [readthedocs.](https://xtb-docs.readthedocs.io/en/latest/CENSO_docs/censorc.html)
You should provide the constraints in your working directory using a file called `constraints.xtb` in the same format as you would [apply constraints in xtb](https://xtb-docs.readthedocs.io/en/latest/xcontrol.html). You should be able to use both `$fix` and `$constrain`. 

Leopold

**Comment by adamhorvath99** [comment]
Oh OK. I will try the next version!

But let me ask a bit related further question. So I hardcoded the constrains in the part2 xtb/orca optimisation input generation. For the ORCA part is was al right, but at the end I got a fully optimised, unconstrained geomerty. The question is that is there a further xtb optimisation during the rrho calculation implemented in CENSO (after the part2 r2scan-3c opt)?
Thank you!

**Comment by lmseidler** [comment]
The old version is using the ANCOPT optimizer in xtb as driver for all geometry optimizations. I guess the constraints you add in the ORCA input are therefore ignored. You need to define the constraints in the xcontrol file for xtb to use them and this is not possible using the old version of CENSO.
For all rrho calculations CENSO uses single-point hessians as long as you have bhess = True.

Leopold
