### ISSUE TITLE
OMP set to at least 4 

### ISSUE THREAD

**Issue by ph283804** [grimme-lab/CENSO#64]
For various reasons, some of which are unclear to me, orca parallelization breaks in some of our cluster's nodes. The workaround we found when dealing with this issue in the previous versions of censo (up to 1.2) was to set omp = 1, so that each orca single point only used one core.

In the current censo version (2.1), It states that "omp has to be a minimum value of 4", which not only makes this workaround impossible but also seems somewhat pointlessly restrictive. Unless this would heavily break the code, would it be possible to lift this restriction and allow omp values of 1, 2 and 3?

EDIT: I see the omp settings were changed in 2.1.1 (and moved elsewhere). Is this restriction also changed in that version or is it still in place?

**Comment by lmseidler** [comment]
In principle it would be possible to use values of less than 4 if you call censo from a python script. There, you could `from censo.params import Config` and set `Config.OMPMIN = 1`. Although this is not intended to be done, it probably won't break anything.

**Comment by lmseidler** [comment]
I will add a command line argument to set `OMPMIN` for the next version. The default will stay 4.
